name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: registry.gitlab.tugraz.at/plasma/images/texlive:full
      credentials:
        username: gitlab+deploy-token-246
        password: mJVsBY_TAmnyzZARM2Tz

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: |
         cd ${{ github.workspace }}/DOC
         latexmk -pdf canonical_and_boozer_flux_coords_via_VMEC.tex
         lyx --export pdf2 neo-orb.lyx
      - name: Upload doc artifacts
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: |
            canonical_and_boozer_flux_coords_via_VMEC.pdf
            neo-orb.pdf
