name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: registry.gitlab.tugraz.at/plasma/images/texlive:full
      credentials:
        username: gitlab+deploy-token-246
        password: mJVsBY_TAmnyzZARM2Tz

    steps:
      - run: lyx
     

